import assert from 'node:assert/strict';
import { chromium } from '@playwright/test';

const browser = await chromium.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true, args: ['--enable-webgl', '--ignore-gpu-blocklist', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
try {
  const page = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.addInitScript(() => {
    localStorage.setItem('coastline-install-dismissed-v2', String(Date.now()));
    window.testPads = [];
    Object.defineProperty(navigator, 'getGamepads', { configurable: true, value: () => window.testPads });
  });
  await page.goto(process.env.TEST_URL || 'http://127.0.0.1:5173');
  await page.waitForFunction(() => window.__coastline && document.querySelector('#loading.loaded'));
  await page.waitForTimeout(700);
  assert.equal(await page.locator('.touch-controls').isVisible(), false, 'Driving controls stay hidden on the menu');
  const connect = () => page.evaluate(() => {
    window.testPads = [null, { index: 1, mapping: 'standard', connected: true, axes: [0, 0, 0, 0], buttons: Array.from({ length: 17 }, () => ({ pressed: false, value: 0 })) }];
  });
  const button = (index, value) => page.evaluate(({ index, value }) => { window.testPads[1].buttons[index] = { pressed: value > .5, value }; }, { index, value });
  const frames = () => page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
  const press = async index => { await button(index, 1); await frames(); await button(index, 0); await frames(); };
  await connect();
  await page.waitForFunction(() => document.body.dataset.controller === 'true');
  assert.equal(await page.locator('.touch-controls').isVisible(), false);
  assert.equal(await page.locator('#welcome .controller-hint').isVisible(), true);
  assert.equal(await page.locator('.touch-hint').isVisible(), false);
  await page.screenshot({ path: '.artifacts/controller-mobile.png' });
  await button(7, .75);
  await page.waitForFunction(() => window.__coastline.started && window.__coastline.vehicle.speed > 3);
  await page.evaluate(() => window.testPads[1].axes[0] = .6);
  await page.waitForFunction(() => window.__coastline.vehicle.steer > .2);
  await page.evaluate(() => window.testPads[1].axes[0] = 0);
  await button(7, 0); await frames();
  await press(9); assert.equal(await page.evaluate(() => window.__coastline.paused), true);
  await button(9, 1); await frames();
  assert.equal(await page.evaluate(() => window.__coastline.paused), false);
  await page.waitForTimeout(200);
  assert.equal(await page.evaluate(() => window.__coastline.paused), false, 'holding Start must not toggle repeatedly');
  await button(9, 0); await frames();
  await press(2); assert.match(await page.locator('#view').getAttribute('aria-label'), /Extra close view/);
  await press(3); assert.equal(await page.evaluate(() => window.__coastline.vehicle.speed), 0);
  await button(6, 1); await page.waitForFunction(() => window.__coastline.vehicle.speed < -1);
  await button(6, 0); await frames();
  for (const selector of ['#change-journey', '#view', '#reset', '#next-journey', '#pause']) {
    assert.equal(await page.locator(selector).isVisible(), false, `${selector} hides with a controller`);
  }
  await press(8);
  const position = await page.evaluate(() => window.__coastline.vehicle.s);
  await button(7, 1); await press(9); await frames();
  assert.equal(await page.evaluate(() => window.__coastline.vehicle.s), position);
  assert.equal(await page.locator('#journey-dialog').isVisible(), true);
  await page.locator('#close-journeys').tap(); await frames();
  assert.equal(await page.evaluate(() => window.__coastline.input.state.forward), false);
  await button(7, 0); await frames(); await button(7, 1); await frames();
  assert.equal(await page.evaluate(() => window.__coastline.input.state.forward), 1);
  await page.evaluate(() => { window.testPads = []; });
  await page.waitForFunction(() => document.body.dataset.controller === 'false');
  assert.equal(await page.evaluate(() => window.__coastline.paused), true);
  assert.equal(await page.locator('.touch-controls').isVisible(), false, 'Driving controls stay hidden while paused');
  assert.equal(await page.evaluate(() => window.__coastline.input.state.forward), false);
  await connect(); await frames(); await press(9);
  assert.equal(await page.evaluate(() => window.__coastline.paused), false);
  await button(7, 1); await frames();
  await page.evaluate(() => window.dispatchEvent(new Event('blur')));
  await frames();
  assert.equal(await page.evaluate(() => window.__coastline.paused), true);
  assert.equal(await page.evaluate(() => window.__coastline.input.state.forward), false);
  await button(7, 0); await frames(); await press(9);
  assert.equal(await page.evaluate(() => window.__coastline.paused), false);
  await page.evaluate(() => { window.testPads = []; }); await frames();
  await page.locator('#resume').tap();
  assert.equal(await page.locator('.touch-controls').isVisible(), true);
  await page.keyboard.down('w');
  await page.waitForFunction(() => window.__coastline.vehicle.speed > 3);
  await page.keyboard.up('w');
  assert.deepEqual(errors, []);
  console.log('Controller detection, analog driving, reverse, shortcuts, menus, disconnect/reconnect, focus loss, touch visibility and keyboard fallback passed (simulated gamepad).');
} finally { await browser.close(); }
