import { chromium } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
await mkdir('.artifacts', { recursive: true });
const browser = await chromium.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true, args: ['--enable-webgl', '--ignore-gpu-blocklist', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, deviceScaleFactor: 1 });
const errors = [];
page.on('pageerror', e => errors.push(e.message));
page.on('console', e => { if (e.type() === 'error') errors.push(e.text()); });
await page.goto('http://127.0.0.1:5173', { waitUntil: 'networkidle' });
await page.waitForFunction(() => window.__coastline && document.querySelector('#loading').classList.contains('loaded'), { timeout: 60000 });
await page.waitForTimeout(1200);
await page.screenshot({ path: '.artifacts/coastline-initial.png' });
console.log(JSON.stringify(await page.evaluate(() => { const a = window.__coastline; return { chunks: a.world.chunks.size, car: a.vehicle.car.position.toArray(), camera: a.rendering.camera.position.toArray(), rendering: a.rendering.renderer.info.render, memory: a.rendering.renderer.info.memory }; }), null, 2));
console.log('Browser errors:', errors);
await browser.close();
